banking_system/banking_system/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("authentication/",include("app_authentication.urls")),
    path("",include("bank_management.urls")),
]

banking_system/app_authentication/models.py
from django.core.validators import RegexValidator
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models


class UserManager(BaseUserManager):
    def create_user(self, account_name, password=None, **extra_fields):
        if not account_name:
            raise ValueError('The Account Name field must be set')
        user = self.model(account_name=self.normalize_email(
            account_name), **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, account_name, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(account_name, password, **extra_fields)

SELF_EMPLOYED_MARRIAGE_CHOICES = [('yes', 'Yes'),('no', 'No'),]
GENDER_CHOICES = [('male', 'Male'),('female', 'Female'),]
PROPERTY_AREA_CHOICES = [('urban', 'Urban'),('semi-urban', 'Semiurban'),('rural', 'Rural'),]
DEPENDENTS_CHOICES = [(0, '0'),(1, '1'),(2, '2'),(3, '3'),(4, '4'),]
EDUCATION_CHOICES = [('graduated', 'Graduate'),('not_graduated', 'Not Graduate'),]

class User(AbstractBaseUser, PermissionsMixin):
    account_name = models.CharField(max_length=30, unique=True)
    pan_number_regex = '^[A-Z]{3}P[A-Z][0-9]{4}K$'
    pan_number_validator = RegexValidator(pan_number_regex,'Account Number must be in the format ABCP1X1234K','invalid')
    pan_number = models.CharField(validators=[pan_number_validator],max_length=11,unique=True,null=False,blank=False)
    phone_regex = '^\+?1?\d{9,15}$'
    phone_validator = RegexValidator(phone_regex,'Phone number must be entered in the format: +999999999. Up to 15 digits allowed.','invalid')
    phone = models.CharField(validators=[phone_validator],max_length=17,null=True,blank=True)
    address = models.CharField(max_length=100, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    self_employed = models.CharField(max_length=3, choices=SELF_EMPLOYED_MARRIAGE_CHOICES,default=SELF_EMPLOYED_MARRIAGE_CHOICES[0][0])
    married = models.CharField(max_length=3, choices=SELF_EMPLOYED_MARRIAGE_CHOICES,default=SELF_EMPLOYED_MARRIAGE_CHOICES[0][0])
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES,default=GENDER_CHOICES[0][0])
    dependents = models.IntegerField(choices=DEPENDENTS_CHOICES,default=DEPENDENTS_CHOICES[0][0])
    education = models.CharField(max_length=13, choices=EDUCATION_CHOICES,default=EDUCATION_CHOICES[0][0])
    applicant_income = models.FloatField()
    co_applicant_income = models.FloatField(blank=True,null=True)
    property_area = models.CharField(max_length=10,choices=PROPERTY_AREA_CHOICES,default=PROPERTY_AREA_CHOICES[0][0])
    email = models.EmailField(blank=True,null=True)
    
    USERNAME_FIELD = 'account_name'
    REQUIRED_FIELDS = ['pan_number','applicant_income']

    objects = UserManager()

    def __str__(self):
        return self.account_name

banking_system/bank_management/models.py
from django.db import models
from app_authentication.models import User
from django.db.models.signals import post_save
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.core.mail import send_mail
from django.conf import settings

# Create your models here.
class Branch(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    code = models.CharField(max_length=10, unique=True)

    class Meta:
        verbose_name_plural = 'Branches'

    def __str__(self):
        return self.name

LOAN_TYPES = (('personal', 'Personal Loan'),('home', 'Home Loan'),('auto', 'Auto Loan'),('student', 'Student Loan'),('business', 'Business Loan'),('line_of_credit', 'Line of Credit'),)

class Loan(models.Model):
    loan_type = models.CharField(max_length=15, choices=LOAN_TYPES)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    paid = models.BooleanField(default=False)
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    availed_by = models.ForeignKey(User, on_delete=models.CASCADE)
    interest_rate = models.PositiveIntegerField(default=0,blank=True,null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    due_at = models.DateTimeField()
    paid_at = models.DateTimeField(blank=True,null=True)
    loan_status = models.CharField(max_length=15,blank=True,null=True)
    credited = models.BooleanField(default=False)

    def __str__(self):
        return f"Loan for {self.availed_by} of amount {self.amount}"

    def get_credit_history(self):
        user = self.availed_by
        user_due_loans = Loan.objects.filter(due_at__lte=timezone.now(),availed_by=user,paid=False)
        if len(user_due_loans)==0:
            return 1
        return 0
        
    def get_loan_amount_term(self):
        return (self.due_at - self.created_at).days

    def get_pay_loan_button(self):
        account = Account.objects.filter(hold_by=self.availed_by).first()
        total_amount = self.amount + (self.amount * self.interest_rate / 100)

        if not self.paid and account:
            return account.balance >= total_amount
        
        return False
    
    def update_loan_status(self):
        user = self.availed_by
        account = Account.objects.filter(hold_by=self.availed_by).first()
        total_amount = self.amount + (self.amount * self.interest_rate / 100)
        user_pending_loans =  Loan.objects.filter(due_at__gte=timezone.now(),availed_by=user,paid=False)
        user_due_loans =  Loan.objects.filter(due_at__lte=timezone.now(),availed_by=user,paid=False)

        # The factors considered for approving the loans for the machine learning testing part are , 
        # 1 ) The account balance must be greater than the loan amount with interest
        # 2 ) The user must be self.employed and graduated
        # 3 ) The user must have zero due loans and less than two pending loans
        # 4 ) The dependents on the users must be 3 or less and his/her income should be greater than 40000

        if (account.balance >= total_amount and 
            user.self_employed and user.applicant_income >= 40000 and 
            user.dependents <=3 and len(user_due_loans) == 0 and
            len(user_pending_loans) <= 50 and user.education == "graduated"):
            self.loan_status = "Approved" # Approved
        else:
            self.loan_status = "Rejected" # Rejected
        

    def save(self, *args, **kwargs):
        if self.loan_status=="Approved" and not self.credited:
            account = Account.objects.filter(hold_by=self.availed_by)[0]
            account.balance+=self.amount
            account.save()
            self.credited=True
        super().save(*args, **kwargs)

    def clean(self):
        if self.due_at<=self.created_at:
            raise ValidationError("Due Date must be greater than created date")
        
    



ACCOUNT_TYPES = (('checking', 'Checking'),('savings', 'Savings'),('money_market', 'Money Market'),('cd', 'Certificate of Deposit'),('credit', 'Credit Card'),('loan', 'Loan'),)

class Account(models.Model):
    account_type = models.CharField(max_length=15, choices=ACCOUNT_TYPES)
    balance = models.DecimalField(max_digits=10, decimal_places=2,default=0)
    hold_by = models.ForeignKey(User, on_delete=models.CASCADE)
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.hold_by}"

TRANSACTION_TYPES = (('DEPOSIT', 'Deposit'),('WITHDRAWAL', 'Withdrawal'),('TRANSFER', 'Transfer'))

class Transaction(models.Model):
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    transaction_type = models.CharField(max_length=20, choices=TRANSACTION_TYPES)
    sent_by = models.ForeignKey(Account, on_delete=models.CASCADE)
    sent_to = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='received_transactions')
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    description = models.CharField(max_length=255,blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.sent_by.hold_by.account_name} sent {self.amount} to {self.sent_to.hold_by.account_name} from {self.branch.name}'

    def save(self,*args,**kwargs):
        if self.sent_by.balance < self.amount:
            raise ValidationError(f"Insufficient Balance in {self.sent_by} account")
        self.sent_by.balance-=self.amount
        self.sent_to.balance+=self.amount
        self.sent_by.save()
        self.sent_to.save()
        super().save(*args,**kwargs)


class Notification(models.Model):
    loan = models.ForeignKey(Loan, on_delete=models.CASCADE,blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.CharField(max_length=90,blank=True)
    date = models.DateTimeField(auto_now_add=True)
    is_seen = models.BooleanField(default=False)

    def __str__(self):
        return f"Notification for {self.user}"


def create_notification_on_loan_creation(sender, instance, created, **kwargs):
    if created:
        loan = instance
        user = loan.availed_by
        message = f"You took a loan of amount \u20B9{loan.amount} from {loan.branch}. The due date is {loan.due_at.date()}."
        email_subject="Loan Request Approved"

        if loan.loan_status=="Rejected":
            message=f"Whoops! Your request for a loan of amount \u20B9{loan.amount} from {loan.branch} was rejected."
            email_subject="Loan Request Rejected"
        
        Notification.objects.create(loan=loan, user=user, message=message)

        # if user.email:
        #     send_mail(subject=email_subject, message=message, from_email=settings.EMAIL_HOST_USER, recipient_list=[user.email])

post_save.connect(create_notification_on_loan_creation, sender=Loan)

def create_notification_on_loan_payment(sender,instance,created,**kwargs):
    loan = instance
    if not created and loan.paid:
        user = loan.availed_by
        message = f"Your loan of \u20B9{loan.amount} from {loan.branch} has been paid off!"
        Notification.objects.create(loan=loan,user=user,message=message)
        if user.email:
            email_subject = "Loan Payed Off!"
            # send_mail(subject=email_subject, message=message, from_email=settings.EMAIL_HOST_USER, recipient_list=[user.email])
post_save.connect(create_notification_on_loan_payment, sender=Loan)

banking_system/banking_system/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
      integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    
    />
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'img/favicon.ico' %}"
      />
    <link rel="stylesheet" type="text/css" href="{% static 'navbar.css' %}" />
    {% block css_sheet %} {% endblock css_sheet %}

    <title>Banking System</title>
  </head>
  <body style="background-color: #e1e9f5">
    <nav>
      <input type="checkbox" id="check" />
      <label for="check" class="checkbtn">
        <i class="fas fa-bars"></i>
      </label>
      <label class="logo">Banking System</label>
      <ul>
        {% comment %} <li><a href="{% url 'index' %}">Home</a></li> {% endcomment %}
        <li><a href="{% url 'loans' %}">Loans</a></li>
        <li><a href="{% url 'branches' %}">Branches</a></li>
        <li><a href="{% url 'loan-request' %}">Request Loan</a></li>
        <li>
          <a href="{% url 'notifications' %}"
            >Notifications {% if request.user.is_authenticated %}
            <!-- prettier-ignore -->
            {% if count_notifications %}
            <span class="badge rounded-pill bg-danger"
              >{{count_notifications}}</span
            >{% endif %} {% endif %}
          </a>
        </li>
        <li><a href="{% url 'my-profile' %}">Profile</a></li>
        <li><a href="{% url 'logout' %}">Logout</a></li>
      </ul>
    </nav>

    <!-- prettier-ignore-->
    {% block content %}  {% endblock content %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

banking_system/banking_system/templates/loan-request-response.html
{% extends 'base.html' %} {% block content %}
<div class="row mt-2" style="width: 100%">
  <div class="col">
    <div
      class="card mt-2"
      style="background-color: #{{bg_color}};
      border: 1px solid #dee2e6;
      border-radius: 0.95rem;
      margin-right: 150px;
      margin-left: 150px;
      box-shadow: 0 0.125rem 0.5rem rgba(0, 0, 0, 0.3);
    "
    >
      <div class="card-body">
        <h3
          class="card-title"
          style="color: #007bff; font-size: 1.25rem; font-weight: bold"
        >
          {% if approved %} Congratulation! The request for loan has been
          approved! {% else %} Whoops! The request for loan was rejected!
          <!-- prettier-ignore -->
          {% endif %}
        </h3>
        <h6 class="card-subtitle mb-2 text-muted">
          Loan Type: {{loan.get_loan_type_display}}
        </h6>
        <p class="card-text">
          <b>Bank Branch</b>: {{loan.branch}} <br /><b>Taken At</b>:
          {{loan.created_at}} <br />
          <b>Due Date</b>: {{loan.due_at}} <br /><b>Loan Amount</b>:
          &#8377;{{loan.amount}} <br /><b>Loan Status</b>: {{loan.loan_status}}
          <br />

          {% if loan.get_loan_amount_term %}

          <b>Loan Amount Term</b>: {{loan.get_loan_amount_term}} <br />

          {% endif %}
        </p>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

banking_system/banking_system/templates/loans.html
{% extends 'base.html' %} {% block content %}
<div class="row mt-2" style="width: 100%">
  <div class="col">
    <!-- prettier-ignore -->
    {% if not pending_loans and not due_loans and not paid_loans and not rejected_loans %}
    <h1 class="mt-4">You dont have any loans as of now</h1>
    {% else %}
    <h1
      class="mt-2 alert alert-primary"
      style="margin-right: 150px; margin-left: 150px"
    >
      My Loans
    </h1>
    {% endif %} {% if pending_loans %}
    <h4
      class="mt-2 alert alert-primary"
      style="margin-right: 150px; margin-left: 150px"
    >
      Pending Loans
    </h4>
    {% for loan in pending_loans %}
    <div
      class="card mt-2"
      style="
        background-color: #f8f9fa;
        border: 1px solid #dee2e6;
        border-radius: 0.95rem;
        box-shadow: 0 0.125rem 0.5rem rgba(0, 0, 0, 0.3);
        margin-right: 150px;
        margin-left: 150px;
      "
    >
      <div class="card-body">
        <h5
          class="card-title"
          style="color: #007bff; font-size: 1.25rem; font-weight: bold"
        >
          Amount: &#8377;{{loan.amount}}
        </h5>
        <h6 class="card-subtitle mb-2 text-muted">
          Loan Type: {{loan.get_loan_type_display}}
        </h6>
        <p class="card-text">
          <b>Bank Branch</b>: {{loan.branch}} <br /><b>Taken At</b>:
          {{loan.created_at}} <br />
          <b>Due Date</b>: {{loan.due_at}} <br /><b>Loan Status</b>:
          {{loan.loan_status}} <br />

          {% if loan.get_loan_amount_term %}

          <b>Loan Amount Term</b>: {{loan.get_loan_amount_term}} <br />

          {% endif %}
        </p>
        {% if loan.get_pay_loan_button %}
        <button
          type="button"
          class="btn btn-outline-primary float-end"
          data-toggle="modal"
          data-target="#addBalanceModal"
        >
          Pay Off Loan
        </button>
        <!-- Add balance modal -->
        <div
          class="modal fade"
          id="addBalanceModal"
          tabindex="-1"
          role="dialog"
          aria-labelledby="addBalanceModalLabel"
          aria-hidden="true"
        >
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="addBalanceModalLabel">
                  Add Balance
                </h5>
                <button
                  type="button"
                  class="close"
                  data-dismiss="modal"
                  aria-label="Close"
                >
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                Are you sure you want to pay off this loan?
              </div>
              <div class="modal-footer">
                <button
                  type="button"
                  class="btn btn-secondary"
                  data-dismiss="modal"
                >
                  Close
                </button>
                <a class="btn btn-primary" href="{% url 'pay-loan' loan.pk %}">
                  Yes , I am sure.
                </a>
              </div>
            </div>
          </div>
        </div>
        {% endif %}
      </div>
    </div>
    {% endfor %} {% endif %} {% if due_loans %}
    <h4
      class="mt-2 alert alert-primary"
      style="margin-right: 150px; margin-left: 150px"
    >
      Due Loans
    </h4>
    {% for loan in due_loans %}
    <div
      class="card mt-2"
      style="
        background-color: #f8f9fa;
        border: 1px solid #dee2e6;
        border-radius: 0.95rem;
        box-shadow: 0 0.125rem 0.5rem rgba(0, 0, 0, 0.3);
        margin-right: 150px;
        margin-left: 150px;
      "
    >
      <div class="card-body">
        <h5
          class="card-title"
          style="color: #007bff; font-size: 1.25rem; font-weight: bold"
        >
          Amount: &#8377;{{loan.amount}}
        </h5>
        <h6 class="card-subtitle mb-2 text-muted">
          Loan Type: {{loan.get_loan_type_display}}
        </h6>
        <p class="card-text">
          <b>Bank Branch</b>: {{loan.branch}} <br /><b>Taken At</b>:
          {{loan.created_at}} <br />
          <b>Due Date</b>:
          <span style="color: red; font-weight: bold">{{loan.due_at}}</span
          ><b>Loan Status</b>: {{loan.loan_status}} <br />
          <br />
        </p>
      </div>
    </div>
    <br />
    {% endfor %} {% endif %}{% if paid_loans %}
    <h4
      class="mt-2 alert alert-primary"
      style="margin-right: 150px; margin-left: 150px"
    >
      Paid Loans
    </h4>
    {% for loan in paid_loans %}
    <div
      class="card mt-2"
      style="
        background-color: #f8f9fa;
        border: 1px solid #dee2e6;
        border-radius: 0.95rem;
        margin-right: 150px;
        margin-left: 150px;
        box-shadow: 0 0.125rem 0.5rem rgba(0, 0, 0, 0.3);
      "
    >
      <div class="card-body">
        <h5
          class="card-title"
          style="color: #007bff; font-size: 1.25rem; font-weight: bold"
        >
          Amount: &#8377;{{loan.amount}}
        </h5>
        <h6 class="card-subtitle mb-2 text-muted">
          Loan Type: {{loan.get_loan_type_display}}
        </h6>
        <p class="card-text">
          <b>Bank Branch</b>: {{loan.branch}} <br /><b>Taken At</b>:
          {{loan.created_at}} <br /><b>Paid At</b>: {{loan.paid_at}}
          <br />
          <b>Loan Amount Term</b>: {{loan.get_loan_amount_term}} (days)
          <br />
          <b>Loan Status</b>: {{loan.loan_status}} <br />
        </p>
      </div>
    </div>
    {% endfor %} {% endif %} {% if rejected_loans %}
    <h4
      class="mt-2 alert alert-primary"
      style="margin-right: 150px; margin-left: 150px"
    >
      Rejected Loans
    </h4>
    {% for loan in rejected_loans %}

    <div
      class="card mt-2"
      style="
        background-color: #f8f9fa;
        border: 1px solid #dee2e6;
        border-radius: 0.95rem;
        margin-right: 150px;
        margin-left: 150px;
        box-shadow: 0 0.125rem 0.5rem rgba(0, 0, 0, 0.3);
      "
    >
      <div class="card-body">
        <h5
          class="card-title"
          style="color: #007bff; font-size: 1.25rem; font-weight: bold"
        >
          Amount: &#8377;{{loan.amount}}
        </h5>
        <h6 class="card-subtitle mb-2 text-muted">
          Loan Type: {{loan.get_loan_type_display}}
        </h6>
        <p class="card-text">
          <b>Bank Branch</b>: {{loan.branch}} <br /><b>Taken At</b>:
          {{loan.created_at}}
          <br />
          <b>Loan Status</b>: {{loan.loan_status}} <br />
        </p>
      </div>
    </div>
    {% endfor %} {% endif %}
  </div>
</div>
{% endblock content %}

banking_system/banking_system/templates/my-profile.html
{% extends 'base.html' %} {% block content %}
<div class="row mt-2" style="width: 100%">
  <div class="col">
    <h1
      class="alert alert-primary"
      style="margin-right: 150px; margin-left: 150px"
    >
      My Profile
    </h1>

    <div
      class="card mt-2"
      style="
        background-color: #f8f9fa;
        border: 1px solid #dee2e6;
        border-radius: 0.95rem;
        box-shadow: 0 0.125rem 0.5rem rgba(0, 0, 0, 0.3);
        margin-left: 150px;
        margin-right: 150px;
      "
    >
      <div class="card-body">
        <h5
          class="card-title"
          style="color: #007bff; font-size: 1.25rem; font-weight: bold"
        >
          Account Name: {{profile.account_name}}
        </h5>
        <h6 class="card-subtitle mb-2 text-muted">
          PAN Number: {{profile.pan_number}}
        </h6>
        <h6 class="card-subtitle mb-2 text-muted">
          Account Type: {{account.get_account_type_display}}
        </h6>
        <p class="card-text">
          <!-- prettier-ignore -->
          {% if profile.phone %} <b>Phone</b> : {{profile.phone}}
          <br /><!-- prettier-ignore -->{% endif %} {% if profile.address %}
          <b>Address</b> : {{profile.address}} <br />{% endif %}

          <b>Balance</b> : &#8377;{{account.balance}} <br />
          <b>Bank Branch</b> : {{account.branch}} <br />
          <b>Gender</b> : {{user.get_gender_display}} <br />
          <b>Education</b> : {{user.get_education_display}} <br />
          <b>Dependents</b> : {{user.get_dependents_display}} <br />
          <b>Self-Employed</b> : {{user.get_self_employed_display}} <br />
          <b>Married</b> : {{user.get_married_display}} <br />
          <b>Property Area</b> : {{user.get_property_area_display}} <br />
          <b>Income</b> : &#8377;{{user.applicant_income}} <br />

          {% if user.co_applicant_income %}

          <b>Co-Applicant Income</b> : &#8377;{{user.co_applicant_income}}
          <br /><!-- prettier-ignore -->{% endif %}
        </p>
        <button
          type="button"
          class="btn btn-outline-primary float-end"
          data-toggle="modal"
          data-target="#addBalanceModal"
        >
          Add Balance
        </button>
        <!-- Add balance modal -->
        <div
          class="modal fade"
          id="addBalanceModal"
          tabindex="-1"
          role="dialog"
          aria-labelledby="addBalanceModalLabel"
          aria-hidden="true"
        >
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="addBalanceModalLabel">
                  Add Balance
                </h5>
                <button
                  type="button"
                  class="close"
                  data-dismiss="modal"
                  aria-label="Close"
                >
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <form
                  method="post"
                  id="addBalanceForm"
                  action="{% url 'add-balance' %}"
                >
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="amount">Amount</label>
                    <input
                      type="number"
                      class="form-control"
                      id="amount"
                      name="amount"
                      required
                    />
                  </div>
                </form>
              </div>
              <div class="modal-footer">
                <button
                  type="button"
                  class="btn btn-secondary"
                  data-dismiss="modal"
                >
                  Close
                </button>
                <button
                  type="submit"
                  form="addBalanceForm"
                  class="btn btn-primary"
                >
                  Add Balance
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}